import datetime
from binance.client import Client as c

aapi_key = "AibX2zigFqfEHTCmuV0pIXtM5rCCk6c2SUnBeF5Hxn78yF40V29n0imCRgV7V5Hq"
aapi_secret = "kLO5DN3Nv38W2uYzBkJrrTpnLfzjCUu8qHhi0gDlkxjk4AsqSHyyrAXxzaUkiS3N"


api_key = "xCTmpTB1thBdiHpLhtHGLbWwE3FBM9f8DeSls1ZOssHnGgh18a2Rustu1aElc41k"
api_secret = "sFq09v9KbFjjGr7QdzwYL56ZoKZmuL3R0adVttTnEUl3AbZPfi0ijo9XDwYi2YPh"

timestamp_base_time = datetime.datetime(year=1970, month=1, day=1)

interval_list = [c.KLINE_INTERVAL_1MINUTE,
                 c.KLINE_INTERVAL_3MINUTE,
                 c.KLINE_INTERVAL_5MINUTE,
                 c.KLINE_INTERVAL_15MINUTE,
                 c.KLINE_INTERVAL_30MINUTE,
                 c.KLINE_INTERVAL_1HOUR,
                 c.KLINE_INTERVAL_2HOUR,
                 c.KLINE_INTERVAL_4HOUR,
                 c.KLINE_INTERVAL_6HOUR,
                 c.KLINE_INTERVAL_8HOUR,
                 c.KLINE_INTERVAL_12HOUR,
                 c.KLINE_INTERVAL_1DAY,
                 c.KLINE_INTERVAL_3DAY,
                 c.KLINE_INTERVAL_1WEEK,
                 c.KLINE_INTERVAL_1MONTH]



symbol_ETH_list = ['AAVEETH', 'ADAETH', 'ADXETH', 'AIONETH', 'BATETH', 'BETHETH', 'BLZETH', 'BNBETH', 'BNTETH', 'BQXETH', 'BRDETH', 'CDTETH', 'CMTETH', 'COVERETH', 'CVCETH', 'CVPETH', 'DASHETH', 'DATAETH', 'DENTETH', 'DEXEETH', 'DFETH', 'EASYETH', 'ELFETH', 'ENJETH', 'EOSETH', 'ETCETH', 'FIROETH', 'FRONTETH', 'FUNETH', 'GHSTETH', 'GLMETH', 'GRTETH', 'GXSETH', 'HEGICETH', 'HOTETH', 'ICXETH', 'IOSTETH', 'IOTAETH', 'IOTXETH', 'KEYETH', 'KMDETH', 'KNCETH', 'LINKETH', 'LOOMETH', 'LRCETH', 'LSKETH', 'LTCETH', 'MANAETH', 'MFTETH', 'MTLETH', 'NANOETH', 'NASETH', 'NCASHETH', 'NEBLETH', 'NEOETH', 'NPXSETH', 'NULSETH', 'OMGETH', 'ONTETH', 'OSTETH', 'PIVXETH', 'POWRETH', 'QKCETH', 'QLCETH', 'QSPETH', 'QTUMETH', 'RENBTCETH', 'REPETH', 'RLCETH', 'SCETH', 'SCRTETH', 'SLPETH', 'SNTETH', 'STEEMETH', 'STMXETH', 'STRAXETH', 'SUSDETH', 'THETAETH', 'TRXETH', 'VETETH', 'VIBETH', 'WANETH', 'WAVESETH', 'WBTCETH', 'XEMETH', 'XLMETH', 'XMRETH', 'XRPETH', 'XVGETH', 'XZCETH', 'ZECETH', 'ZENETH', 'ZILETH', 'ZRXETH']

symbol_BNB_list = ['AAVEBNB', 'ADABNB', 'ALGOBNB', 'ALPHABNB', 'ANKRBNB', 'ANTBNB', 'ARPABNB', 'ATOMBNB', 'AVABNB', 'AVAXBNB', 'AXSBNB', 'BAKEBNB', 'BANDBNB', 'BATBNB', 'BCHBNB', 'BELBNB', 'BLZBNB', 'BTTBNB', 'BURGERBNB', 'CAKEBNB', 'CELRBNB', 'CHRBNB', 'CHZBNB', 'COCOSBNB', 'COSBNB', 'COTIBNB', 'CREAMBNB', 'CRVBNB', 'CTKBNB', 'CTSIBNB', 'DASHBNB', 'DGBBNB', 'DIABNB', 'DOTBNB', 'EGLDBNB', 'ENJBNB', 'EOSBNB', 'ETCBNB', 'FETBNB', 'FILBNB', 'FIOBNB', 'FTMBNB', 'FTTBNB', 'HARDBNB', 'HBARBNB', 'HOTBNB', 'ICXBNB', 'INJBNB', 'IOSTBNB', 'IOTABNB', 'IQBNB', 'JSTBNB', 'KAVABNB', 'KP3RBNB', 'KSMBNB', 'LTCBNB', 'LUNABNB', 'MATICBNB', 'MBLBNB', 'MFTBNB', 'MITHBNB', 'MKRBNB', 'NEARBNB', 'NEOBNB', 'NMRBNB', 'OCEANBNB', 'OGNBNB', 'ONEBNB', 'ONTBNB', 'PAXGBNB', 'PERLBNB', 'PROMBNB', 'RSRBNB', 'RUNEBNB', 'RVNBNB', 'SANDBNB', 'SCBNB', 'SNXBNB', 'SOLBNB', 'SPARTABNB', 'SRMBNB', 'STMXBNB', 'STXBNB', 'SUSHIBNB', 'SWRVBNB', 'SXPBNB', 'THETABNB', 'TROYBNB', 'TRXBNB', 'UNFIBNB', 'UNIBNB', 'VETBNB', 'VTHOBNB', 'WABIBNB', 'WANBNB', 'WAVESBNB', 'WINBNB', 'WINGBNB', 'WNXMBNB', 'WRXBNB', 'WTCBNB', 'XLMBNB', 'XMRBNB', 'XRPBNB', 'XTZBNB', 'XVSBNB', 'YFIBNB', 'YFIIBNB', 'ZECBNB', 'ZENBNB', 'ZILBNB']

symbol_BTC_list = ['1INCHBTC', 'AAVEBTC', 'ADABTC', 'ADXBTC', 'AERGOBTC', 'AGIBTC', 'AIONBTC', 'AKROBTC', 'ALGOBTC', 'ALPHABTC', 'AMBBTC', 'ANKRBTC', 'ANTBTC', 'APPCBTC', 'ARDRBTC', 'ARKBTC', 'ARPABTC', 'ASRBTC', 'ASTBTC', 'ATMBTC', 'ATOMBTC', 'AUDIOBTC', 'AVABTC', 'AVAXBTC', 'AXSBTC', 'BALBTC', 'BANDBTC', 'BATBTC', 'BCDBTC', 'BCHBTC', 'BCPTBTC', 'BEAMBTC', 'BELBTC', 'BLZBTC', 'BNBBTC', 'BNTBTC', 'BOTBTC', 'BQXBTC', 'BRDBTC', 'BTCSTBTC', 'BTGBTC', 'BTSBTC', 'BZRXBTC', 'CDTBTC', 'CELOBTC', 'CELRBTC', 'CHRBTC', 'CHZBTC', 'CKBBTC', 'CNDBTC', 'COMPBTC', 'COSBTC', 'COTIBTC', 'CRVBTC', 'CTKBTC', 'CTSIBTC', 'CTXCBTC', 'CVCBTC', 'DASHBTC', 'DATABTC', 'DCRBTC', 'DGBBTC', 'DIABTC', 'DLTBTC', 'DNTBTC', 'DOCKBTC', 'DOGEBTC', 'DOTBTC', 'DREPBTC', 'DUSKBTC', 'EGLDBTC', 'ELFBTC', 'ENJBTC', 'EOSBTC', 'ETCBTC', 'ETHBTC', 'EVXBTC', 'FETBTC', 'FILBTC', 'FIOBTC', 'FIROBTC', 'FLMBTC', 'FORBTC', 'FTMBTC', 'FTTBTC', 'FUNBTC', 'GASBTC', 'GLMBTC', 'GOBTC', 'GRSBTC', 'GRTBTC', 'GTOBTC', 'GVTBTC', 'GXSBTC', 'HARDBTC', 'HBARBTC', 'HIVEBTC', 'HNTBTC', 'ICXBTC', 'IDEXBTC', 'INJBTC', 'IOSTBTC', 'IOTABTC', 'IOTXBTC', 'IRISBTC', 'JSTBTC', 'JUVBTC', 'KAVABTC', 'KMDBTC', 'KNCBTC', 'KSMBTC', 'LINKBTC', 'LOOMBTC', 'LRCBTC', 'LSKBTC', 'LTCBTC', 'LTOBTC', 'LUNABTC', 'MANABTC', 'MATICBTC', 'MDABTC', 'MDTBTC', 'MITHBTC', 'MKRBTC', 'MTHBTC', 'MTLBTC', 'NANOBTC', 'NASBTC', 'NAVBTC', 'NBSBTC', 'NEARBTC', 'NEBLBTC', 'NEOBTC', 'NKNBTC', 'NMRBTC', 'NULSBTC', 'NXSBTC', 'OAXBTC', 'OCEANBTC', 'OGBTC', 'OGNBTC', 'OMGBTC', 'ONEBTC', 'ONGBTC', 'ONTBTC', 'ORNBTC', 'OSTBTC', 'OXTBTC', 'PAXGBTC', 'PERLBTC', 'PHBBTC', 'PIVXBTC', 'PNTBTC', 'POABTC', 'POLYBTC', 'POWRBTC', 'PPTBTC', 'PSGBTC', 'QKCBTC', 'QLCBTC', 'QSPBTC', 'QTUMBTC', 'RCNBTC', 'RDNBTC', 'REEFBTC', 'RENBTC', 'RENBTCBTC', 'REPBTC', 'REQBTC', 'RIFBTC', 'RLCBTC', 'ROSEBTC', 'RSRBTC', 'RUNEBTC', 'RVNBTC', 'SANDBTC', 'SCBTC', 'SCRTBTC', 'SKLBTC', 'SKYBTC', 'SNGLSBTC', 'SNMBTC', 'SNTBTC', 'SNXBTC', 'SOLBTC', 'SRMBTC', 'STEEMBTC', 'STMXBTC', 'STORJBTC', 'STPTBTC', 'STRAXBTC', 'STXBTC', 'SUNBTC', 'SUSDBTC', 'SUSHIBTC', 'SXPBTC', 'SYSBTC', 'TCTBTC', 'TFUELBTC', 'THETABTC', 'TNBBTC', 'TOMOBTC', 'TRBBTC', 'TROYBTC', 'TRUBTC', 'TRXBTC', 'TWTBTC', 'UMABTC', 'UNFIBTC', 'UNIBTC', 'UTKBTC', 'VETBTC', 'VIABTC', 'VIBBTC', 'VIBEBTC', 'VIDTBTC', 'VITEBTC', 'WABIBTC', 'WANBTC', 'WAVESBTC', 'WBTCBTC', 'WINGBTC', 'WNXMBTC', 'WPRBTC', 'WRXBTC', 'WTCBTC', 'XEMBTC', 'XLMBTC', 'XMRBTC', 'XRPBTC', 'XTZBTC', 'XVGBTC', 'XVSBTC', 'XZCBTC', 'YFIBTC', 'YFIIBTC', 'YOYOBTC', 'ZECBTC', 'ZENBTC', 'ZILBTC', 'ZRXBTC']

symbol_USDT_list = ['1INCHUSDT', 'AAVEUSDT', 'ADAUSDT', 'AIONUSDT', 'AKROUSDT', 'ALGOUSDT', 'ALPHAUSDT', 'ANKRUSDT', 'ANTUSDT', 'ARDRUSDT', 'ARPAUSDT', 'ASRUSDT', 'ATMUSDT', 'ATOMUSDT', 'AUDIOUSDT', 'AUDUSDT', 'AVAUSDT', 'AVAXUSDT', 'AXSUSDT', 'BALUSDT', 'BANDUSDT', 'BATUSDT', 'BCHUSDT', 'BEAMUSDT', 'BELUSDT', 'BLZUSDT', 'BNBUSDT', 'BNTUSDT', 'BTCSTUSDT', 'BTCUSDT', 'BTSUSDT', 'BTTUSDT', 'BUSDUSDT', 'BZRXUSDT', 'CELOUSDT', 'CELRUSDT', 'CHRUSDT', 'CHZUSDT', 'CKBUSDT', 'COCOSUSDT', 'COMPUSDT', 'COSUSDT', 'COTIUSDT', 'CRVUSDT', 'CTKUSDT', 'CTSIUSDT', 'CTXCUSDT', 'CVCUSDT', 'DASHUSDT', 'DATAUSDT', 'DCRUSDT', 'DENTUSDT', 'DGBUSDT', 'DIAUSDT', 'DNTUSDT', 'DOCKUSDT', 'DOGEUSDT', 'DOTUSDT', 'DREPUSDT', 'DUSKUSDT', 'EGLDUSDT', 'ENJUSDT', 'EOSUSDT', 'ETCUSDT', 'ETHUSDT', 'EURUSDT', 'FETUSDT', 'FILUSDT', 'FIOUSDT', 'FIROUSDT', 'FLMUSDT', 'FTMUSDT', 'FTTUSDT', 'FUNUSDT', 'GBPUSDT', 'GRTUSDT', 'GTOUSDT', 'GXSUSDT', 'HARDUSDT', 'HBARUSDT', 'HIVEUSDT', 'HNTUSDT', 'HOTUSDT', 'ICXUSDT', 'INJUSDT', 'IOSTUSDT', 'IOTAUSDT', 'IOTXUSDT', 'IRISUSDT', 'JSTUSDT', 'JUVUSDT', 'KAVAUSDT', 'KEYUSDT', 'KMDUSDT', 'KNCUSDT', 'KSMUSDT', 'LINKUSDT', 'LRCUSDT', 'LSKUSDT', 'LTCUSDT', 'LTOUSDT', 'LUNAUSDT', 'MANAUSDT', 'MATICUSDT', 'MBLUSDT', 'MDTUSDT', 'MFTUSDT', 'MITHUSDT', 'MKRUSDT', 'MTLUSDT', 'NANOUSDT', 'NBSUSDT', 'NEARUSDT', 'NEOUSDT', 'NKNUSDT', 'NMRUSDT', 'NPXSUSDT', 'NULSUSDT', 'OCEANUSDT', 'OGNUSDT', 'OGUSDT', 'OMGUSDT', 'ONEUSDT', 'ONGUSDT', 'ONTUSDT', 'ORNUSDT', 'OXTUSDT', 'PAXGUSDT', 'PAXUSDT', 'PERLUSDT', 'PNTUSDT', 'PSGUSDT', 'QTUMUSDT', 'REEFUSDT', 'RENUSDT', 'REPUSDT', 'RIFUSDT', 'RLCUSDT', 'ROSEUSDT', 'RSRUSDT', 'RUNEUSDT', 'RVNUSDT', 'SANDUSDT', 'SCUSDT', 'SKLUSDT', 'SNXUSDT', 'SOLUSDT', 'SRMUSDT', 'STMXUSDT', 'STORJUSDT', 'STPTUSDT', 'STRAXUSDT', 'STXUSDT', 'SUNUSDT', 'SUSDUSDT', 'SUSHIUSDT', 'SXPUSDT', 'TCTUSDT', 'TFUELUSDT', 'THETAUSDT', 'TOMOUSDT', 'TRBUSDT', 'TROYUSDT', 'TRUUSDT', 'TRXUSDT', 'TUSDUSDT', 'TWTUSDT', 'UMAUSDT', 'UNFIUSDT', 'UNIUSDT', 'USDCUSDT', 'UTKUSDT', 'VETUSDT', 'VITEUSDT', 'VTHOUSDT', 'WANUSDT', 'WAVESUSDT', 'WINGUSDT', 'WINUSDT', 'WNXMUSDT', 'WRXUSDT', 'WTCUSDT', 'XEMUSDT', 'XLMUSDT', 'XMRUSDT', 'XRPUSDT', 'XTZUSDT', 'XZCUSDT', 'YFIIUSDT', 'YFIUSDT', 'ZECUSDT', 'ZENUSDT', 'XVSUSDT', 'ZILUSDT', 'ZRXUSDT']

symbol_TRX_list = ['BTTTRX', 'WINTRX']

symbol_XRP_list = ['TRXXRP']

